### PR TITLE
Update localities and neighbourhood records

### PR DESCRIPTION
**Pull request by stepps00**
Will fix https://github.com/whosonfirst-data/whosonfirst-data/issues/1910.

This PR will:

- [x] Update existing neighbourhoods in Baghdad
- [x] Create new neighbourhoods in Baghdad
- [x] Update existing localities in Baghdad
- [x] Create new neighbourhoods in Baghdad
- [x] Update English and Arabic names, and wof:name properties for all updated records
- [x] PIP to update all hierarchy and parent_id properties
- [x] Validate all geojson/properties

### CODE REVIEW

**Comment by stepps00** [comment]
I still need to PIP and validate properties/geometries before merging, but assigning for review. Here are a few screenshots of new locality polygon coverage in Iraq:

Screen Shot 2022-10-27 at 4 14 51 PM
Screen Shot 2022-10-27 at 4 14 59 PM
Screen Shot 2022-10-27 at 4 15 13 PM

**Comment by nvkelso** [comment]
🎉

**Review by nvkelso — APPROVED** [review]
I reviewed sample of these records and they look good, and we looked at the new geoms and deprecations heads up in QGIS and those look good.

**Comment by stepps00** [comment]
The most recent commits validate all geometries in this repo, correcting them when invalid, and include all the PIP work needed to update hierarchies/parent_ids. I'm going to QA a bit more, then merge.

**Pull request merged**
